# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\x1a\x1bgoogle/protobuf/empty.proto\"@\n\nMediaChunk\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"D\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\ncontent_id\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x0e\x43ontentRequest\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\"4\n\nStatistics\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\x12\x12\n\nview_count\x18\x02 \x01(\x05\"S\n\x0b\x43ontentInfo\x12\x12\n\ncontent_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x13\n\x0buploaded_at\x18\x04 \x01(\t\"1\n\x0c\x43ontentsList\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.media.ContentInfo2\xfe\x01\n\x0cMediaService\x12\x39\n\rUploadContent\x12\x11.media.MediaChunk\x1a\x13.media.UploadStatus(\x01\x12;\n\rStreamContent\x12\x15.media.ContentRequest\x1a\x11.media.MediaChunk0\x01\x12\x39\n\rGetStatistics\x12\x15.media.ContentRequest\x1a\x11.media.Statistics\x12;\n\x0cListContents\x12\x16.google.protobuf.Empty\x1a\x13.media.ContentsListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIACHUNK']._serialized_start=51
  _globals['_MEDIACHUNK']._serialized_end=115
  _globals['_UPLOADSTATUS']._serialized_start=117
  _globals['_UPLOADSTATUS']._serialized_end=185
  _globals['_CONTENTREQUEST']._serialized_start=187
  _globals['_CONTENTREQUEST']._serialized_end=223
  _globals['_STATISTICS']._serialized_start=225
  _globals['_STATISTICS']._serialized_end=277
  _globals['_CONTENTINFO']._serialized_start=279
  _globals['_CONTENTINFO']._serialized_end=362
  _globals['_CONTENTSLIST']._serialized_start=364
  _globals['_CONTENTSLIST']._serialized_end=413
  _globals['_MEDIASERVICE']._serialized_start=416
  _globals['_MEDIASERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
